-- 보호소에서 중성화한 동물

SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME  FROM ANIMAL_INS as a LEFT JOIN ANIMAL_OUTS as b ON a.ANIMAL_ID = b.ANIMAL_ID WHERE a.SEX_UPON_INTAKE LIKE '%Intact%' AND b.SEX_UPON_OUTCOME NOT LIKE '%Intact%' ORDER BY a.ANIMAL_ID

-- 말이 너무 헷갈렷음 ㅠㅠㅠㅠㅠㅠ